### ISSUE TITLE
(1.0+0.0im)/(0.0+0.0im) returns ComplexNaN

### ISSUE THREAD

**Issue by pearlzli** [scheinerman/RiemannComplexNumbers.jl#1] opened 2015-07-10 20:18 UTC
Hi, I'm using your package and getting a mysterious result. After adding `println("Division called")` before the first line of `/(w::Complex, z::Complex)`:

```julia
julia> using RiemannComplexNumbers

julia> (1 + 0im)/(0 + 0im)
Division called
ComplexInf

julia> (1.0 + 0.0im)/(0 + 0im)
division called
ComplexInf

julia> (1 + 0im)/(0.0 + 0.0im)
Division called
ComplexInf

julia> (1.0 + 0.0im)/(0.0 + 0.0im)
ComplexNaN
```

I was able to get around this by defining another division method,
```julia
function /(w::Complex{Float64}, z::Complex{Float64})
    println("Alternate division called")
    # Same function body as /(w::Complex, z::Complex)
end
```
after which I got
```julia
julia> (1.0 + 0.0im)/(0.0 + 0.0im)
Alternate division called
ComplexInf
```
although curiously adding the method `/{T<:FloatingPoint}(w::Complex{T}, z::Complex{T})` had no effect, i.e. `(1.0+0.0im)/(0.0+0.0im)` returned just `ComplexNaN` as before.

**Comment by scheinerman** [comment] 2015-07-11 20:19
Thanks for pointing this out. The problem is (and I don't fully understand why) that when `(1.0 + 0.0im)/(0.0 + 0.0im)` is evaluated, the complex division baked into Julia is used and my division code is not executed. Your solution would work, of course, but I wonder what other divisions would also bypass my code. For example:
```julia
julia> u = complex128(1); z = complex128(0); u/z
ComplexNaN
```
Also wrong! I wonder how many special cases would need to be handled. 

Curiously, this works: `(1+0im)/(0+0im)` 

I'll attempt to fix, but this is *mostly* a demonstration project that shows an alternative way to handle complex infinity in Julia. I'm hoping a more expert programmer does a rewrite so the numerics are better than what I have here, perhaps by calling the base numerics after doing checks.

**Comment by scheinerman** [comment] 2015-07-12 18:35
This problem is fixed, I think. The solution was to [re]define the various arithmetic operations *outside* the `RiemannComplexNumbers` module so they actually override the corresponding methods in `Base`. I'm going to close this issue but if you find it's broken, we can reopen and try again.

**Closed by scheinerman** 2015-07-12 18:35 UTC

**Comment by pearlzli** [comment] 2015-07-13 13:15
Thanks!
